# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3f4455daad7dfe00330560e65b12727c235920383a2ee5822ac5f3e3472dd359623a507eeab2c74ca55e27dd548d1a410d6d805dee04b8034bc4a9be0ac16db5

test:
  secret_key_base: 759d02f5131f2b8ad3edc76bcd5352d85e64ab4c927a3ce18e333fd7d6ea75912c6877412f2b8c2d5be7c9a6f4d66a9879cd699037128852d940c3fc3d4061cc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
